// Generate TypeScript types from the JSON Schemas in ../contracts.
//
// The generated file is checked in, so a contract change shows up twice: as a
// diff in src/data/contract.gen.ts and as type errors wherever the site uses a
// field that changed. Run `npm run types` after the contract changes.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const WEB = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CONTRACTS = resolve(WEB, "..", "contracts");
const OUT = join(WEB, "src", "data", "contract.gen.ts");

const SCHEMAS = [
  ["index.schema.json", "RunIndex"],
  ["snapshot.schema.json", "Snapshot"],
  ["track_record.schema.json", "TrackRecordSummary"],
];

/** Replace every {"$ref": "#/$defs/x"} with the definition itself. The $defs
 *  are tiny (a date pattern, a 0-1 number), and naming them would produce
 *  clashing types such as `Date`, which would hide JavaScript's own Date. */
function inlineDefs(node, defs) {
  if (Array.isArray(node)) return node.map((item) => inlineDefs(item, defs));
  if (node === null || typeof node !== "object") return node;
  if (typeof node.$ref === "string" && node.$ref.startsWith("#/$defs/")) {
    return inlineDefs(defs[node.$ref.slice("#/$defs/".length)], defs);
  }
  const out = {};
  for (const [key, value] of Object.entries(node)) {
    if (key !== "$defs") out[key] = inlineDefs(value, defs);
  }
  return out;
}

const parts = [
  "// GENERATED by scripts/gen-types.mjs from ../contracts/*.schema.json. Do not edit by hand.\n" +
    "/* eslint-disable */\n",
];
for (const [file, name] of SCHEMAS) {
  const raw = JSON.parse(readFileSync(join(CONTRACTS, file), "utf8"));
  const schema = inlineDefs(raw, raw.$defs ?? {});
  // Name the root type ourselves rather than deriving it from the schema title.
  schema.title = name;
  parts.push(await compile(schema, name, { bannerComment: "", additionalProperties: false, format: false }));
}
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, parts.join("\n"));
console.log(`Wrote ${OUT}`);
