// GENERATED by scripts/gen-types.mjs from ../contracts/*.schema.json. Do not edit by hand.
/* eslint-disable */

/**
 * What the latest run did for each league, and where its snapshot is. Contract version 1.x; see contracts/README.md.
 */
export interface RunIndex {
contract_version: string
generated_at: string
history_path: string
competitions: {
id: string
name: string
file: (string | null)
status: ("updated" | "kept_previous" | "no_snapshot")
snapshot_generated_at: (string | null)
data_through: (string | null)
provisional: (boolean | null)
error: (string | null)
}[]
}

/**
 * One league's state and predictions after one run of `python -m tabletalk update`. Contract version 1.x; see contracts/README.md for the meaning of every field and the versioning rules.
 */
export interface Snapshot {
contract_version: string
competition: {
id: string
name: string
country: string
season: string
}
generated_at: string
data_through: (string | null)
latest_result: (null | {
date: string
home_team: string
away_team: string
home_goals: number
away_goals: number
})
provisional: boolean
notices: string[]
run: {
seed: number
seed_rule: string
n_simulations: number
code_commit: (string | null)
code_dirty: (boolean | null)
config_hash: string
config_files: string[]
model: {
fitted_through: (string | null)
promoted_strategy: string
promoted_teams: string[]
strength_uncertainty: string
match_predictions: string
}
}
sources: {
loader: string
role: ("results" | "fixtures" | "context" | "check")
params: {

}
}[]
zones: {
id: string
label: string
/**
 * @minItems 1
 */
positions: [number, ...(number)[]]
}[]
table: {
position: number
team: string
played: number
won: number
drawn: number
lost: number
goals_for: number
goals_against: number
goal_difference: number
points: number
points_deducted: number
}[]
teams: {
team: string
position_now: number
points_now: number
expected_points: number
points_p10: number
points_p90: number
expected_position: number
zones: {
[k: string]: number
}
/**
 * @minItems 1
 */
finishing_positions: [number, ...(number)[]]
}[]
upcoming_matches: {
match_id: (string | null)
matchday: (string | null)
date: (string | null)
kickoff_utc: (string | null)
status: (string | null)
home_team: string
away_team: string
probabilities: {
home: number
draw: number
away: number
}
expected_goals: {
home: number
away: number
}
likely_scorelines: {
home: number
away: number
probability: number
}[]
}[]
}

/**
 * Locked predictions scored against results (track_record/summary.json). Contract version 1.1.0+; see contracts/README.md.
 */
export interface TrackRecordSummary {
contract_version: string
generated_at: string
live_since: (string | null)
chain_verified: true
counts: {
locks: number
voided: number
invalid: number
missed: number
scored: number
awaiting_result: number
awarded_not_scored: number
}
competitions: {
id: string
n: number
comparisons: {
against: ("base rates" | "market")
n: number
model_log_loss: (number | null)
other_log_loss: (number | null)
diff: (number | null)
ci95: (number | null)
first_half: (number | null)
second_half: (number | null)
verdict: ("no scored matches yet" | "too few matches to compare" | "no detectable difference" | "model better" | "model worse" | "consistently better but modest" | "consistently worse but modest")
matches_needed: (number | null)
}[]
}[]
calibration: {
outcome: ("home" | "draw" | "away")
bin: string
n: number
mean_forecast: number
observed: number
ci_low: number
ci_high: number
gap: number
}[]
matches: {
lock_id: string
competition: string
home_team: string
away_team: string
kickoff_utc: (string | null)
predicted_at: string
probabilities: {
home: number
draw: number
away: number
}
home_goals: number
away_goals: number
log_loss: number
code_commit: (string | null)
}[]
notes: string[]
}
